name: Keep Alive Supabase

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          echo "🔄 Ping a Supabase REST API..."
          curl -f -s -i "https://xtribcsicgyzjyhvsia.supabase.co/rest/v1/" \
            -H "apikey: sb_publishable_qr4QprFfqrtklogBhez-Lw_hT9VRAID" \
            -H "Authorization: Bearer sb_publishable_qr4QprFfqrtklogBhez-Lw_hT9VRAID"
